### ISSUE TITLE
import pods gives error

### ISSUE THREAD

**Issue by Atulsingh92** [sods/ods#24]
Hello, 

A simple` import pods` gives the following error in my python 3.8

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\aus1n19\Anaconda3\lib\site-packages\pods-0.0.32a0-py3.8.egg\pods\__init__.py", line 1, in <module>
    from . import datasets
  File "C:\Users\aus1n19\Anaconda3\lib\site-packages\pods-0.0.32a0-py3.8.egg\pods\datasets.py", line 19, in <module>
    logging.basicConfig(
  File "C:\Users\aus1n19\Anaconda3\lib\logging\__init__.py", line 1976, in basicConfig
    h = FileHandler(filename, mode)
  File "C:\Users\aus1n19\Anaconda3\lib\logging\__init__.py", line 1143, in __init__
    StreamHandler.__init__(self, self._open())
  File "C:\Users\aus1n19\Anaconda3\lib\logging\__init__.py", line 1172, in _open
    return open(self.baseFilename, self.mode, encoding=self.encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\tmp\\sods.log'
``` 

I tried installing with `pip install pods` , however I get the following warning 
```
Requirement already satisfied: pods in c:\users\aus1n19\anaconda3\lib\site-packages\pods-0.0.32a0-py3.8.egg (0.0.32a0)
Requirement already satisfied: pandas in c:\users\aus1n19\anaconda3\lib\site-packages (from pods) (1.2.4)
Requirement already satisfied: PyYAML in c:\users\aus1n19\anaconda3\lib\site-packages (from pods) (5.4.1)
Requirement already satisfied: scipy in c:\users\aus1n19\anaconda3\lib\site-packages (from pods) (1.6.2)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\aus1n19\anaconda3\lib\site-packages (from pandas->pods) (2.8.1)
Requirement already satisfied: numpy>=1.16.5 in c:\users\aus1n19\anaconda3\lib\site-packages (from pandas->pods) (1.20.2)
Requirement already satisfied: pytz>=2017.3 in c:\users\aus1n19\anaconda3\lib\site-packages (from pandas->pods) (2021.1)
Requirement already satisfied: six>=1.5 in c:\users\aus1n19\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->pods) (1.15.0)
Note: you may need to restart the kernel to use updated packages.
WARNING: Error parsing requirements for cftime: [Errno 2] No such file or directory: 'c:\\users\\aus1n19\\anaconda3\\lib\\site-packages\\cftime-1.5.0.dist-info\\METADATA'
```

Can someone help?

**Comment by lawrennd** [comment]
Have you tried a 

`pip uninstall --yes pods` 

followed by a reinstall?

**Comment by FlyinTeller** [comment]
@lawrennd The issue is [https://github.com/sods/ods/blob/3b91f06c649ec9bcb7ea2a37b8aa217643a2dd3f/pods/datasets.py#L22](here). The path is hard coded and evaluates to `C:\tmp` which does not exist in windows per default

**Comment by Atulsingh92** [comment]
So `pip uninstall --yes pods` and then a reininstalled, installs the library without any errors. However, `import pods` still gives the same error as mentioned in the previous post.  No changes.

**Comment by lawrennd** [comment]
Thanks @FlyinTeller .... that looks like something I added without thinking too much ... 

Any guidance for how that line should be set up (e.g. is there an environment variable across windows/Linux/OSX that would give a good steer for where to put that file?

@Atulsingh92 that implies a quick hack might be to create c:\tmp can you let us know if that fixes? That would prove that @FlyinTeller  is right.

**Comment by Atulsingh92** [comment]
Yes, indeed. Creating C:\tmp folder (and having write permissions to it) does the trick. I can import pods now.
